name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true  # Enforce Node.js 20

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js  # Step to set up Node.js
      uses: actions/setup-node@v4  # Use the latest version of the setup-node action
      with:
        node-version: '20'  # Specify Node.js version 20

    - name: Checkout repository  # Step to check out the repository
      uses: actions/checkout@v4  # Use the latest version of the checkout action

    - name: Set up C++ environment  # Step to set up the C++ environment
      run: |
        sudo apt-get update  # Update package lists
        sudo apt-get install -f  # Attempt to fix broken dependencies
        sudo apt-get install -y g++ clang-format lcov valgrind  # Install g++, clang-format, lcov, and valgrind


    - name: Check code formatting  # Step to check code formatting
      run: |
        find includes src -name '*.hpp' -o -name '*.cpp' | xargs clang-format -style=file -output-replacements-xml | grep "<replacement " && echo "Code is not formatted" && exit 1 || echo "Code is formatted"

    - name: Create bin directory  # Step to create the bin directory
      run: mkdir -p bin  # Create the bin directory if it doesn't exist

    - name: Compile main program  # Step to compile the main program
      run: make  # Compile the main program

    - name: Run main program  # Step to run the main program
      run: |
        if [ -f ./bin/Train ]; then
          ./bin/Train input/railNetworkPrintFolder/railNetworkPrintGood.txt input/trainPrintFolder/trainPrintGood.txt
        else
          echo "main binary not found"
          exit 1
        fi

    - name: Compile Singleton tests with coverage  # Step to compile Singleton tests with coverage flags
      run: g++ -Wall -Wextra -std=c++14 --coverage -o bin/testSingleton tests/SingletonTest.cpp  # Compile the Singleton tests with coverage flags

    - name: Run Singleton tests  # Step to run Singleton tests
      run: |
        if [ -f ./bin/testSingleton ]; then
          ./bin/testSingleton
        else
          echo "testSingleton binary not found"
          exit 1
        fi

    - name: Compile Node tests with coverage  # Step to compile Node tests with coverage flags
      run: g++ -Wall -Wextra -Werror -g --coverage -o bin/testNode tests/NodeTest.cpp src/Node.cpp  # Compile the Node tests with coverage flags

    - name: Run Node tests  # Step to run Node tests
      run: |
        if [ -f ./bin/testNode ]; then
          ./bin/testNode
        else
          echo "testNode binary not found"
          exit 1
        fi

    - name: Run main program with Valgrind  # Step to run the main program with Valgrind
      run: |
        if [ -f ./bin/Train ]; then
          valgrind --leak-check=full --show-leak-kinds=all ./bin/Train input/railNetworkPrintFolder/railNetworkPrintGood.txt input/trainPrintFolder/trainPrintGood.txt
        else
          echo "main binary not found"
          exit 1
        fi

    - name: Run Singleton tests with Valgrind  # Step to run Singleton tests with Valgrind
      run: |
        if [ -f ./bin/testSingleton ]; then
          valgrind --leak-check=full --show-leak-kinds=all ./bin/testSingleton
        else
          echo "testSingleton binary not found"
          exit 1
        fi

    - name: Run Node tests with Valgrind  # Step to run Node tests with Valgrind
      run: |
        if [ -f ./bin/testNode ]; then
          valgrind --leak-check=full --show-leak-kinds=all ./bin/testNode
        else
          echo "testNode binary not found"
          exit 1
        fi

    - name: Generate coverage report  # Step to generate coverage report
      run: |
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        genhtml coverage.info --output-directory coverage

    - name: Upload coverage report  # Step to upload coverage report
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: coverage-report-${{ github.run_number }}
        path: coverage
        if-no-files-found: warn
        compression-level: 6
        overwrite: true
        include-hidden-files: false
